### ISSUE TITLE
Tracking of currently engineered modules

### ISSUE THREAD

**Issue by rosscarlson** [msarilar/EDEngineer#156]
Add a page/section called "Module Management".  This would show you:
- What modules you have engineered by module type (regardless if they are in storage or on a ship)
- When expanded you'd see each one by class.  So say you expand "Frame Shift Drive" you'd see "Class 3, Class 5, Class 6" in a list below
- Expand the specific module and you'd see the changes you have compared to the possible changes for that specific item

I'd imagine the interface could look something like this where you'd click to expand each level (so I've clickd on "Class 5" then on "Grade 5" to see the details)

Frame Shift Drive
+ Class 3
+ Class 5
+--Grade 5
+----[B]Mass: 40% | 45%/20%[/B]  (bold to indicate a possible issue, see below)
+----Integrity: -16% | -25%/-12%
+----Power Draw: 16% | 25%/11%
+----[B]Optimized Mass: 24% | 20%/50%[/B] (bold to indicate a possible issue, see below)
+ Class 6

Power Plant
+ Class 2
+ Class 3
+ Class 4

(and so on)

That way you could look through your modules and see what you have and if you want to go change something.  Say you want to build a super fast Eagle you could look through what you have and see what modules you'd either use or want to go tweak for that.

Take it a bit further and the app could auto alert you of possible bad changes.  Say anything that's worse or better than 75% possible for that system.  So in my example above both Mass and Optimized Mass are in bold as they are something the commander should likely review.  Perhaps that 75% isn't the right threshold and hell perhaps even that is user definable but that might be a bit unnecessary.

No clue if the logs contain this data or if it would need to be entered manually ala the first time you run the app and need to confirm it's inventory to what's in your ship.

**Comment by elijahgill** [comment]
This information might be available from the Frontier account. I know EliteDangerousDataProvidor can export your ships to Coriolis with engineer modification info. It does have the user sign in to the Frontier account. The Android app "EVA" (Elite Virtual Assistant) has a similar feature with Frontier account log in. Obviously the Android app cannot access the local log files on the PC. Links below

https://github.com/cmdrmcdonald/EliteDangerousDataProvider

https://play.google.com/store/apps/details?id=com.lightroomplugins.eva

**Comment by msarilar** [comment]
afaik the commander's logs do not output the % results of any blueprint craft, they just tell the fact that the blueprint has been crafted

as @elijahgill says, this information is probably available through an API which was used by an official free mobile application : https://www.facebook.com/EliteDangerousOfficial/posts/10154861126185564

this app has since then been removed but the API it used to communicate with is still up and running. Someone basically recreated the application with EVA (charging money for it...). However, even if that API exposes lots of interesting data, it has some issues:

* It is not documented
* Frontier seems to want to put it in the bin and replace it with the commander's logs (by progressively adding new logs to make it redundant with the API)
* It would require EDEngineer to request user login/password, which I don't like at all and will never happen

Some solutions would be:
* Frontier should document the API and make it clear that it's okay for third parties to use it (currently you basically have to retro-engineer it)
* Frontier should keep adding event logs with more information (they're doing that but it moves really slowly)
* If they decide to go back to the API, they must change how authentication is done. Players should be able to generate a token from their account, choosing what they want to expose (for example, only modules and ships ; exluding cargo information etc...). This token would be used to extract data from the API by third parties, and that way we wouldn't have to use the password directly. This is how [EVE Online](http://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/authentication.html) does it, and that's the right way to do authentication (tokens with an optional expiration exposing specific data).

**Comment by rosscarlson** [comment]
Interesting reply and issues.  First I have to agree that asking for the user's login information isn't a direction you'd want to go in, makes perfect sense.  That said I'm not sure if you use EDDI (if not you're doing it wrong) as there is a feature in EDDI called Shipyard that shows you all the ships you own.  You can click a link next to the ship and it will export the build to Corolios which not only shows you which modules you have installed but what the modifications to those modules are.  EDDI does ask for your Frontier login so perhaps that's how they are pulling the data.

If that's the case and you don't want to get that login data you could also consider an importer for the Corolois data.  Corolios can export to JSON which you could then import into EDE.  Not as elegant as something automated and could keep track of your ships changes in real time but damn close enough for me anyway.  The Module Manager could show a time/date stamp next to the ship so you'd know when the last time you exported it would be.  You import and it shows you all the stuff I detailed about your ship's engineered modules.

**Comment by rosscarlson** [comment]
The more I think about the idea of a Module Manager the more and more I like it.  I think there are several other features that could be added:

- It could show you what modules on what ships you still have as unmodified
- It could auto create shopping lists based on a specific ship.  You could tell EDE what engineers you have unlocked and at what levels.  It could use that and your material/data to show you what mods you can make to a specific ship
- It could predict how "good" of a ship you could craft based on the current material/data you have

So like above:

Shipyard
+ Anaconda
+ FDL
+ Courier
+-- Core
+---- Thrusters: Stock, Grade 3 Possible
+---- Powerplant: Grade 1 applied, Grade 3 available
+---- FSD: Grade 5 applied
+---- Dist: Stock (nothing available)
+---- Life Support: Grade 1 applied, Grade 5 possible
+-- Weapons
+----- Multicannon: Medium, Grade 5 applied
+----- Multicannon: Large, Stock, Grade 5 possible
+----- Beam Laser: Medium, Grade 3 applied, Grade 3 possible

Applied is obvious, available means you can go engineer that module right now and possible means you have the engineer unlocked to that level but you don't have the mats/data to do it.

Hell in some ways Module Manager could be an app all on it's own, given all the data EDE has around this I do think it's a very natural fit.

**Comment by rkodey** [comment]
For what it's worth...  After trying EDEngineer a few weeks back, I was inspired to process the Journal files exactly for the purpose of tracking Modules & Enhancements on my ships.  Basically...  Just what this thread is discussing!

So, kudos to EDEngineer for the inspiration - it's a great app!!

Weirdly, because I keep my gaming rig clean of development tools, I ended up writing a simple script that windows could execute natively using cscript.exe.  It happens to be JavaScript - but (I think) could be easily ported to .NET.

If it would be helpful to anyone, I would be happy to upload it here for comment / ideas...  but of course it's a SUPER-rough script.  I never figured there would be any interest!  I suppose I could spend some time describing the main approach, and the special cases I encountered along the way.

Here's the top-level to see if it's an approach that's interesting:
- I loop through all the Journal files
- regex match the events that matter
- perform operations, including tracking Ships, Modules on each Ship, Enhancements to each Module, and Swapping and Storage of Modules
- Then, I write a "Ships.html" file that shows everything

Known problems:
- Like EDEngineer, the script is only aware of what's in the Journal.  So, modules you bought/modified before the Journal started are not covered.
- Engineer Enhancements are logged in the Journal generically without designating a particular Slot/Module.  So, if you have 6 Shield Boosters, there's no way that I've found to figure out which one received the enhancement.

So...  I have no idea if it would be helpful or not.  But, it's at least a proof-of-concept I suppose.
Any interest?

**Comment by jvml** [comment]
Any tool is better than no tool! I don't have a problem with such an app using the login, you can always change the password. I use the EDDI export to coriolis feature and would love to be able to filter these results by module parameters and size.

**Comment by rkodey** [comment]
Ok...  You asked for it!  :)
https://github.com/rkodey/ED-Modules
