### ISSUE TITLE
[Heads Up] - Upcoming journal changes

### ISSUE THREAD

**Issue by Athanasius** [msarilar/EDEngineer#159]
https://forums.frontier.co.uk/showthread.php/275151-Commanders-log-manual-and-data-sample?p=5088943&viewfull=1#post5088943

"Advance notice of a change to a couple of PlayerJournal entries in 2.3

The code for various nested arrays of records within an event record has been rewritten for consistency. Some events are affected, they now have an array of records with an entry for each material, rather than a record with material names used as value names. All Json key names should now be fixed strings, not material or commodity names. This also allows localisation of the material names. The affected events are:
o	EngineerCraft (Ingredients)
o	Scan (Materials)
o	Synthesis (Materials)

Examples of new syntax:
{ "timestamp":"2017-01-31T10:32:03Z", "event":"Synthesis", "Name":"Repair Basic", "Materials":[ {"Name":"iron", "Count":2}, {"Name":"nickel", "Count":1 } ] }

{ "timestamp":"2017-01-31T10:32:03Z", "event":"EngineerCraft", "Engineer":"Elvira Martuuk", "Blueprint":"FSD_LongRange", "Level":2, "Ingredients":[{"Name":"praseodymium", "Count"1}, {"Name":"disruptedwakeechoes", "Count":3 }, {"Name":"chemicalprocessors", "Count":2 }, {"Name":"arsenic", "Count":2} ] }

A full update to the reference manual will be made when v2.3 beta is released."

**Comment by msarilar** [comment]
Thanks for the heads up!

**Comment by msarilar** [comment]
so these logs are coming first in 2.3 beta ; if you're in it (or if anyone else is), that'd be great to have sample logs so I can try it out (unless frontier's documentation is exhaustively updated).

edengineer will entirely skip logs from the beta so this won't break anything and the application's update will only be required for when 2.3 will actually be released

**Comment by Athanasius** [comment]
Yes, I'll have access (Premium Beta backer).  Remind me when you've heard the beta has started.

**Comment by Athanasius** [comment]
Here's a log that neatly contains the new "current inventory" events and some engineering: https://miggy.org/games/elite-dangerous/misc/Athanasius_2.3beta1_Journal.170301181057.01.log

**Comment by msarilar** [comment]
great stuff, thanks! do you have a similar log but with a non-empty cargo event?

**Comment by Athanasius** [comment]
https://miggy.org/games/elite-dangerous/misc/Athanasius_2.3beta1_Journal.170228164652.01.log

There's only the one stack in cargo there (happened to be in cargo when FDev took the live copy for the beta).  As it's an array it should be enough to confirm the structure.

**Comment by msarilar** [comment]
So I pushed the necessary changes to handle these new logs based on your links. Currently there's no particular optimization (it reads the dump events like any other ones) because I don't think that's necessary as the file reading and parsing is very fast.

Something that'd be awesome is if you could test it on your end by pulling master, I don't know if you have VS Community installed. If you can't test, that's all right of course, but if you do make sure to change [that method "`static bool VersionIsBeta(string line)`"](https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Utils/System/LogWatcher.cs#L163) such that it always return false (other wise the application will keep ignoring beta logs).
