### ISSUE TITLE
Attempt to modify protected registry key

### ISSUE THREAD

**Issue by Athanasius** [msarilar/EDEngineer#161]
In just running EDEngineer, and it updating, it's caused this Comodo PFW popup:

EDEngineer.exe could not be recognized and it is about to modify protected registry key HKUS\S-1-(rest of my per user GUID)\Software\Microsoft\SystemCertificates\CA

Any idea why it's messing with that all of a sudden ?  Blocking this with Comodo PFW also seems to have (or this latest update did) me to lose all settings and favourites.  I still have /some/ counts of amounts of data/materials, but I will need to check if it's lost the "manual changes" data.

**Comment by msarilar** [comment]
I haven't pushed any new release since 10 days, current version is 1.0.4.6 (https://raw.githubusercontent.com/msarilar/EDEngineer/master/EDEngineer/releases/EDEngineer.application)

EDEngineer doesn't touch the registry and even if it would, it could only touch the `HKEY_CURRENT_USER` registry (otherwise it would need admin rights)

try reinstalling the application and check the certificate shown by your browser when accessing the link above (should be a cert from DigiCert granted to Github 
![image](https://cloud.githubusercontent.com/assets/5569959/22509034/a4f4a6f8-e88c-11e6-8337-eb12028a328f.png))

**Comment by Athanasius** [comment]
I'd guess that it *looking* like it had an update was due to losing settings ?

The direct evidence of losing settings was:

1) Language selection popup
2) Window in default position (on my primary monitor, not where it should be on secondary as usual)
3) Window started in Locked mode (I have it unlocked usuall)
4) All favourite blueprints and shopping list forgotten.

I'm antsy about the registry key thing because of it being in the per-use CA store.  Any cert in there could start being part of spoofing any other cert.

**Comment by Athanasius** [comment]
FWIW, all my material counts were still correct.  Some data ones were off, but it had been a while since I last checked those were correct.

**Comment by Athanasius** [comment]
And yes, in Chrome, it's that certificate, but we've only checked the name, not the SHA2 hash or any such.  This is a red herring anyway as I *denied* the registry key change.

**Comment by Athanasius** [comment]
Subsequent runs, again blocking the attempt to modify that registry key have kept all (now-current) settings (no language pop-up, window in correct position and unlocked).

I should note that I did have a hard lockup of my PC yesterday, BUT then after reboot ran EDEngineer without any of these issues.  It was then a 100% normal shutdown before booting up today and encountering this.
