### ISSUE TITLE
Which blueprints an item is contained in

### ISSUE THREAD

**Issue by JetCheOff** [msarilar/EDEngineer#184]
I would like to be able to select a Material or Data item and see which blueprints it is used in. That way I can decide whether or not to keep that item and/or how many. 

If something is only included in blueprints that I don't see myself needing or using at the moment, I can get rid of or adjust the amounts accordingly, that way I can have more of the items I need, without getting rid of items I may need in the near future. Since both Material and Data storage are full.

**Comment by msarilar** [comment]
that's a feature that has been asked many times, and I understand how useful it can be. however it would complexify the GUI quite a bit and I always fear [feature creep](https://en.wikipedia.org/wiki/Feature_creep).

some ingredients are used in lots of blueprints (the most basic materials can be in up to ~30 blueprints) while others are only used in a single one. to represent that data it needs a very cunning design from a UX point of view to make it easy to use, clear to read and not confusing for new users.

until I find a good solution, your best bet would be to use the [local API](https://github.com/msarilar/EDEngineer/wiki/API-Reference) to somewhat extract the data you're looking for with tools like excel or whatever

**Comment by BeckyYork** [comment]
What I've noticed is that materials are used in specific Patterns & Grades.
For example all the Light Weight Grade 5 (except lightweight armour) have the same components.
The same is true for Efficient, over charged, reinforced etc.
If you could add into the mouse over the distinct list of "Pattern Name Grade N" to the mouse over this would be very helpful without adding complex UI elements.
You don't need to list all the different modules that pattern name can be used on.

**Comment by Loadstone** [comment]
I'll leave the same comment I left on the FDev forums:

The "Ingredient Filter" is extremely useful when I'm deciding what to keep and what to throw away when my mats and data fill up, but it's also cumbersome to dig into the dropdowns like that. I'd ask that the highlighted selections map to those checked in the Ingredient Filter (and vice versa), which would give a quick and intuitive way to see what blueprints are related to selected data/mats.

It seemed so intuitive to me that I was shocked it doesn't behave that way. Is there some other functionality tied to the highlighting of data/mats or is it purely cosmetic?

I'm leery of asking for additional settings options since as a general rule that makes it harder for new users. However, as you mention, this is a common feature request. So, how about a setting for "Map Highlighted Data/Materials to Ingredient Filter" which checks/unchecks the highlighted/unhighlighted item(s) when the user changes their highlight state. This would allow more accessible use of the existing Ingredient Filter but could be disabled for users who don't want this. It also lets user tie in with the other filters (for example, I'm always running filters for blueprints grade 3-5 regardless, so it's less likely to clutter the UI with many blueprints).

**Comment by msarilar** [comment]
deployed in 1.6.0.0 !
