### ISSUE TITLE
Closing all mods on the shopping list makes it impossible to see anything.

### ISSUE THREAD

**Issue by MoofinSeeker** [msarilar/EDEngineer#211]
I made a long list of mods for my threshold numbers, expanded the shopping list to see all the materials, then closed all of the mods I have added. Now I can't see the mod list anymore or adjust the size of the box where the shopping list was.

![image](https://cloud.githubusercontent.com/assets/4653424/25071959/8edea45e-22bb-11e7-994a-7e1e5e564622.png)

The black area where my cursor is was where the shopping list was before I closed all the mods for it.

**Comment by MoofinSeeker** [comment]
Update: Restarting fixes it, but it breaks my workflow for what I'm doing.

**Comment by msarilar** [comment]
interesting bug, fixed in ce83406 (available next update, probably tomorrow)

meanwhile you want to make sure to double click on the red slider before you're emptying the shopping list (double clicking on it makes the size of the shopping list automatic so it will properly collapse after being emptied)

**Comment by msarilar** [comment]
published in 1.0.6.7
