### ISSUE TITLE
2.4 Update : New synthesis recipes

### ISSUE THREAD

**Issue by CMDR-Cometborne** [msarilar/EDEngineer#255]
There are a number of new recipes for 2.4:

Limpets:
Basic 10 iron+10 nickel -> 4 limpets (was 10 iron + 10 tin in closed beta but was changed)
(no standard/premium)

Chaff refill:
basic: 1 compact composites, 1 filament composites -> 50% refill
standard: 1 compact composites, 2 filament composites, 1 thermic alloys -> 100% refill
premium:  1 compact composites, 2 filament composites, 1 thermic alloys, 1 proto radiolic alloys -> 100% refill, +2 seconds duration 

Heat sink refill:
basic: 2 basic conductors, 2 heat conduction wiring -> 50% refill
standard:  2 basic conductors, 2 heat conduction wiring, 2 heat exchangers -> 100% refill, +15% heat dissapation
premium: 2 basic conductors, 2 heat conduction wiring, 2 heat exchangers, 1 proto heat radiators -> 100% refill, +30% heat dissapation

life support refill:
basic: 2 iron + 1 nickel -> 100% refill
no standard/premium options

See also [https://github.com/EDDiscovery/EDDiscovery/issues/1229](https://github.com/EDDiscovery/EDDiscovery/issues/1229) for a list of material name changes in 2.4

**Comment by msarilar** [comment]
Hi,

Thanks for the heads up!

Anyone is more than welcome to edit the resource files and submit a pull request 😉. I'll check the integrity of the data (not its truthfulness) and deploy the update as soon as it's ready.

Resource files for EDEngineer are located in [this folder](https://github.com/msarilar/EDEngineer/tree/master/EDEngineer/Resources/Data):

- The blueprints file contains information about blueprints and synthesis, [here's an example of an existing synthesis](https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/blueprints.json#L14206)

- [Ingredients](https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/entryData.json) should also be updated with the new names you referenced in issue 1229 of EDDiscovery

- *Very important!* If ingredient names are updated, their corresponding entries in the [localization file](https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/localization.json#L49) should also be kept up to date otherwise the dynamic translation happening in the application for available languages won't work. Updating the translation doesn't need to be done at the same time (most likely will be done by native speakers of the available languages), just the key of each block requires to be kept in sync with the `entryData.json` file

**Comment by CMDR-Cometborne** [comment]
Finally getting around to this.  Do you prefer separate pull requests for each of the four categories or one pull request with all of them?

The new ingredients were fortunately already added by somebody else, but we need various new origins (Thargoid Ship Scanning, Thargoid Surface Structure Scanning, Thargoid Ship Salvage, Thargoid Scavenger Salvage, Thargoid Surface POI)

**Comment by msarilar** [comment]
Yes a single PR is perfect!
Regarding the new origins, don't hesitate to update the origin list in the ingredient file (entryData.json). I'll make it work afterwards with new icons and localization.
