### ISSUE TITLE
Tracking of material location

### ISSUE THREAD

**Issue by rosscarlson** [msarilar/EDEngineer#256]
Not sure if feature requests/ideas go here - if not apologies.  

When EDE sees a material added to the ship it should record the location.  System would be great, SOI (where) would be even better (if it can know you dropped in on a High Grade USS great).  If not you could link the fact that we know material X is found in USSes so when you tell me the system and USS I know a lot of where to look.

This could be fed to a live database that would show where, when and how many of a material were discovered.  Commanders could search that and know that a player just found a material in a specific location.  This could be HUGE for the community.

This could be done in a very automated way so the commander would need only opt into the feature.  A databases/web front-end is needed and I'd be happy to offer/create that piece.  I think this could be a rather impactful feature.

**Comment by Gimi1967** [comment]
I suspect that this would be much easier to do in EDDiscovery. A db is already in place, and the whole journal is parsed and available. It may well be possible to extract the information already using the field filter in EDDiscovery. Also, EDDiscovery already sends and receives data from EDDN and EDSM.
Presenting your idea over [there ](https://github.com/EDDiscovery/EDDiscovery) may be a good idea.

**Comment by rosscarlson** [comment]
Certainly not a bad idea, don't really care where it gets added.  I do think if such a thing were created integrating a front end into EDE would be awesome.  The shopping list could then not only tell you what to get but how/where to get it. That would be HUGE for new commanders (and old alike).

**Comment by msarilar** [comment]
It's a good idea that would definitely improve the quality of life of elite's players even more, although I must agree with @Gimi1967 that the scope might be too big for a little tool like EDEngineer which doesn't have the infrastructure to host a live database where players could upload their data.

There are some facts to take into account:
* I think I've read somewhere that an online API is on its way (or is it already live?) which could make other programmers write their own version of material tracking software without having to install anything (e.g. something like inara but that automatically updates) which might render EDEngineer obsolete in the near future
* I've actually stopped playing the game since a while now ; even though I might come back one day to see what new things have been added it's far from certain (at least not in the near future). While I'll keep doing basic maintenance (fixing breaking bugs or merging PR's which update the reference data like new blueprints and stuff like that), I won't be working on new features myself

All in all I think the suggestion should be forwarded to the EDDN guys which sort of centralizes all of players' data in a single data repository. 

Thanks
