### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by killzoid23** [msarilar/EDEngineer#258]
Whenever I try to install, I get a popup like this one.
![verifying jpg-550x0](https://user-images.githubusercontent.com/27360121/30598481-09fc2550-9d17-11e7-885a-dc17befcff91.jpg)

Then this one pops up.

![capture](https://user-images.githubusercontent.com/27360121/30598034-fc5fb660-9d15-11e7-8d95-4121b2df827d.PNG)

I've tried all the wiki troubleshooting tips and running as admin.

**Comment by msarilar** [comment]
Right click the setup.exe, then Properties

Do you have an "Unlock" button or something similar?

**Comment by jeffreywedwards** [comment]
I'm having the same problem. There is no "Unblock" button in the setup.exe properties on Windows 10.

**Comment by msarilar** [comment]
I pushed a small update to add some signing information as well as using the manifest for trust information ; not sure this will fix your problem but worth a try

if it doesn't solve the issue you might want to try to run the setup.exe from the command line 

![image](https://user-images.githubusercontent.com/5569959/30609524-eb024c8c-9d7b-11e7-87ff-4914902e6479.png)

**Comment by jeffreywedwards** [comment]
Still not working for me.

**Comment by killzoid23** [comment]
Same results running from command prompt.

**Comment by msarilar** [comment]
You might want to try from an elevated (admin) terminal, or fiddle with your security/UAC settings (`Control Panel\System and Security\Security and Maintenance`) such that it gives you a fair warning with a "bypass" option instead of completely block the installer.

Apart from that, I don't see how else I could help as it's related to the security configuration of your Windows. I could give you the certificate I used to sign the app which you could add to your trusted root but I really don't feel comfortable doing that; let's try to find another way :)

**Comment by killzoid23** [comment]
Same popups running command prompt as admin. I've tried all 4 of these UAC settings.
![capture2](https://user-images.githubusercontent.com/27360121/30614435-a6c867be-9d48-11e7-9a04-5bea08a6a1a3.PNG)

**Comment by jeffreywedwards** [comment]
Change "HKLM\SOFTWARE\MICROSOFT\.NETFramework\Security\TrustManager‌​\PromptingLevel\Inte‌​rnet" to Enabled

via

https://superuser.com/questions/1252575/unable-to-install-clickonce-application-due-to-security-settings-windows-10

**Comment by msarilar** [comment]
thanks @jeffreywedwards for finding the solution!
I've updated the wiki to include this information
