### ISSUE TITLE
Portuguese Translate

### ISSUE THREAD

**Issue by Wlaspec** [msarilar/EDEngineer#262]
Hello, I'm a member of the translation team of Elite Dangerous for Brazilian Portuguese, we want to help you add the Portuguese version to ED Engineer. How can we do that?

**Comment by msarilar** [comment]
Hi,

You should take a look at the localization file here : https://github.com/msarilar/EDEngineer/blob/master/EDEngineer/Resources/Data/localization.json

Everything is in here, the file is dynamically interpreted by the software once started so no code change is needed, only that json file requires updating (you can edit in your browser and submit a pull request, but I'd recommend using console git with your own text file editor ; it doesn't change anything for me but it might be more comfortable for you guys).

For example:

```json
    "Available Voices:": {
      "es": null,
      "de": "verfügbare Stimmen",
      "fr": null,
      "ru": "Доступные голоса:",
      "pl": "Dostępne głosy:"
},
```

When `Available Voices` is supposed to be displayed to the user, it will show `verfügbare Stimmen` if the user has the german language selected but it won't translate it for spanish and french because the value here is `null` (not `"null"` by the way, just `null`).

Good luck!

**Comment by rafaelpivatto** [comment]
Hello guys, about the code location to brazilian portuguese, what the correct id: "pt", "br", "pt-BR"?

What the software expects to run?

Regards.

**Comment by msarilar** [comment]
Yes `pt` is the correct code to match the `TwoLetterISOLanguageName` property

**Comment by rafaelpivatto** [comment]
Thanks msarilar

;)

**Comment by Wlaspec** [comment]
Translation completed, sending soon.
