### ISSUE TITLE
Unknown Material.

### ISSUE THREAD

**Issue by BeckyYork** [msarilar/EDEngineer#272]
On start up - please don't spam this message.

I had to click it about 200 times to open the app.

The causing problem has gone away with 1.0.8.4 because they materials have been updated but... we don't want to go through that again if fdev introduce something new.

**Comment by msarilar** [comment]
Yeah I need to figure out a way to signal the issue to the user (to make them annoyed enough so they report the issue) without making the entire app almost unusable.

I don't want to silently ignore it and just add the unknown code to the list of ingredient otherwise it would take ages for people to report it. In the 2.4 update I believe it was pretty swift even though it got a bit slower compared to the past.

**Comment by hairagon** [comment]
same issue here. It is unclear if this is being investigated and resolved.
Can this be addressed please?

**Comment by JohnXaverius** [comment]
I have idea. Open the right panel and make a screenshots of all material in this section. And if we find material that no one has yet, it will be easier to add it to EDEngineer. Eventually, then I can compare it with my own MaterialStore and find it in my GameLogs. Or anyone else can compare it.

**Comment by msarilar** [comment]
haven't fixed the initial issue but if you're getting these messages again then I assuem means new materials have been discovered?

**Comment by msarilar** [comment]
fixed in latest update for upcoming Elite Dangerous updates
