### ISSUE TITLE
Would be awesome to have a filter for engineer access level

### ISSUE THREAD

**Issue by Gerdofal** [msarilar/EDEngineer#284]
I know it would mean a new tab or UI window, but I'd love to have a filter to show what I can make based on my access level to engineers. A place where I can put in access level for each engineer and then it only shows recipes to which I have access.

**Comment by msarilar** [comment]
quite tricky to do since you can lose your engineers ranks (experimental rolls); would be best to be handled automatically to avoid human mistakes

ideally the journal would dump all engineers progress, just like it dumps your cargo whenever you start the game. no idea if it's the case though, but I believe there's already an event to handle engineer progress.

lots of changes required since as of today journal updates only affect your cargo in EDEngineer

**Comment by Gerdofal** [comment]
The journal only updates engineer progress when it changes unfortunately.

**Comment by msarilar** [comment]
now irrelevant with 3.0 changes
