### ISSUE TITLE
Option to Change install locaion

### ISSUE THREAD

**Issue by mearmortal** [msarilar/EDEngineer#298]
Is it possible to determine install location, I want to install it to another drive/directory for my convenience?

**Comment by NamtarOberon** [comment]
Yes that would be nice. I can't even find where the app is installed, maybe I am dumb. 
My intent is to wipe it off my PC to install it somewhere different. I did use the normal uninstall, but I have no idea if it removed it completely.

**Comment by msarilar** [comment]
it's commonly asked but it's not something I can control unless I write some custom deployment code since it currently uses ClickOnce with the updates being hosted directly on GitHub (I use https://rawgit.com/ to point at the release files in the project)

such change would (I think) require everybody to uninstall and reinstall new binaries to keep up with the auto-update flow

as of right now, I don't think it matters much. consider the app as a standalone executable that auto-updates (it installs in your AppData folder instead of Program Files, such that it doesn't require any administrative privileges).
