### ISSUE TITLE
Update ED Engineer to read the new ED 3.0 journals.

### ISSUE THREAD

**Issue by Gimi1967** [msarilar/EDEngineer#306]
I'm taking the liberty of adding some change requests based on the updates in ED 3.0.
This is based on the changes seen in ED beta 3.0.

Update ED Engineer to read the new ED 3.0 journals.

Implement relevant changes in ED 3.0 journals.

Updated documentation for ED 3.0 beta journals is available here:

[https://forums.frontier.co.uk/showthread.php/401661-Journal-Documentation-for-v3-0](https://forums.frontier.co.uk/showthread.php/401661-Journal-Documentation-for-v3-0)

[Journal_Manual_v15.pdf](https://github.com/msarilar/EDEngineer/files/1710325/Journal_Manual_v15.pdf)
I expect that a final Journal Manual (v16) will be released when ED 3.0 is released.

**Comment by rosscarlson** [comment]
+1 - I'm also having trouble using it at all, it seems it won't update properly or at least not timely.  A few times it's updated based on my stock but it's been wrong most of the time since the update.

Not complaining as I know it's a lot of work, I just rely on it very heavily so hoping it's not a difficult fix.

**Comment by msarilar** [comment]
released in 1.0.9.1
