### ISSUE TITLE
Blank Window

### ISSUE THREAD

**Issue by Athanasius** [msarilar/EDEngineer#35]
The latest update is giving me blank, black window contents, in either locked or unlocked mode.

OS is Win10 64bit

**Comment by Alekhoff** [comment]
Same for me on Win 10 Pro 64 bit.

**Comment by Alekhoff** [comment]
Any way to roll back a version so i can use this amazing program until the bug is fixed ?

**Comment by msarilar** [comment]
Yes sorry ! I changed the layout a bit and it turns out Windows doesn't really like transparency and changes... I pushed a hot fix that will reset your position window and size. Nothing else is lost, and you'll benefit from the previous update (read the patchnote).

Update your app by restarting it :)

**Comment by Alekhoff** [comment]
Wow, that was fast! Thanks
