### ISSUE TITLE
App crashes when adding Experimental to shopping list

### ISSUE THREAD

**Issue by JimLindsey** [msarilar/EDEngineer#378]
When adding an experimental to the shopping list, the app crashes, then continues to crash when relaunching EDEngineer.  Reverting to previous version or completely removing/ reinstalling will stop the cycle.  
![edengineer_appcrash](https://user-images.githubusercontent.com/24573164/38765429-45e756b4-3f8f-11e8-8512-33446f4c1f76.png)

**Comment by msarilar** [comment]
could you check out the event viewer logs (as described here https://github.com/msarilar/EDEngineer/issues/310#issuecomment-370152359)? most likely there's something about EDEngineer there that could shed some light on the issue.

**Comment by msarilar** [comment]
thanks that's quite useful

do you have any specific details about your configuration (OS version, particular setting in EDEngineer, ...) ?

in the screenshot, I've noticed this :
![image](https://user-images.githubusercontent.com/5569959/38797251-34bd2974-415e-11e8-84d7-15d2f6c93f33.png)

the red/green rectangle should be these characters : ✖ and ✔️

did these characters disappear when the error triggered or did you never see them correctly?

**Comment by f16v1per** [comment]
Windows 7 update [KB2729094]([url]https://www.microsoft.com/en-us/download/details.aspx?id=30566(url)) did the trick!  It seems windows 7 does not segoe ui symbols installed by default like windows 8 and 10.

**Comment by msarilar** [comment]
all right interesting! I'm not sure that it's linked to the initial problem (the app's crash) but we never know. by looking at the logs you provided I definitely see an error but it comes from Windows' framework and not my own code.

let's keep this issue opened in case anyone find something 👍

**Comment by Mikie1729** [comment]
I'm having the exact same problem, the latest version crashed after adding bunch of upgrades to the shopping list and on adding the first experimental effect - boom. It can no longer start at all. Win7 64. Description from Event Viewer is attached. There are two errors immediately one after the other, first one referring to Kernel something, and second one seems related to .Net.

KB2729094 refuses to install on my computer saying that it's not applicable. The symbols were displayed correctly before this issue, so that may not be my problem anyway.

Is there a way to install an older version of EDE? I don't seem to be smart enough to figure it out on my own.

[EDE-crash event.txt](https://github.com/msarilar/EDEngineer/files/1922703/EDE-crash.event.txt)

**Comment by msarilar** [comment]
Is it systematic? I mean if you uninstall, reinstall and add a blueprint to the shopping list, does it systematically crash?

**Comment by msarilar** [comment]
I had an idea that _might_ work to show some details about the error although I'm not sure it will ; could you try to launch the app again (it will prompt for an update), you might get a proper error window with some more details

**Comment by Mikie1729** [comment]
Did that, it happened as you said. But that's as far as it went, it still crashes at the starting graphic screen. Error text (from Win7):
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	EDEngineer.exe
  Problem Signature 02:	1.0.0.0
  Problem Signature 03:	5ad7b564
  Problem Signature 04:	WindowsBase
  Problem Signature 05:	4.7.2114.0
  Problem Signature 06:	59a63fd3
  Problem Signature 07:	df5
  Problem Signature 08:	33
  Problem Signature 09:	System.ArgumentException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	3081
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by JimLindsey** [comment]
Sorry for the delayed response.   I am running Windows 7  Ultimate (64-bit).  Nothing out of the ordinary with my setup that I am aware of.  The X and ✓ are not showing.  
I just updated to version x.21 and it happened right after starting, (not sure if Experimentals were previously selected and expanded, (but not added to shopping list)).  I tried reverting back to previous version and this time it did not correct the error.   Completely removing all traces of the application, ( including any eden prefixes in Apps/2.0), and reinstalling does correct the error.  Here are a couple of sets of the crash logs:   
[AppCrash_logs.zip](https://github.com/msarilar/EDEngineer/files/1930557/AppCrash_logs.zip)

**Comment by JimLindsey** [comment]
Sorry, hit close by mistake

**Comment by msarilar** [comment]
All right I'm a bit clueless about the problem although very curious as to what could be going wrong.
The logs definitely show an issue with the application but unlike other reported problems in the past I can't figure out what's the root cause as the logs only relate to Windows internal machinery.

I think the last resort would be for one of you (users experiencing the problem) to debug the code themselves using visual studio ([community edition, it's free](https://www.visualstudio.com/thank-you-downloading-visual-studio/?sku=Community&rel=15)).

As it seems to affect only Windows 7 users for some reason, you'll need to fork/clone this specific branch https://github.com/msarilar/EDEngineer/tree/task/no-toast-code (I've removed the toast code which isn't available on Windows 7 platform) and not the `master` branch. 

If anyone having the issue is willing to try to debug the application themselves and is having questions or is encountering compilation errors or other technical problems before the application can run, feel free to ask in the dedicated thread https://github.com/msarilar/EDEngineer/issues/308

**Comment by JimLindsey** [comment]
I already have Visual Studios, but I admit I am not very fluent with programming language that uses the .NET  libraries.  I am old school- Pascal, Fortran IV, machine language, but a quick study; so if you point me in a direction I will be more than happy to help however I can.

**Comment by msarilar** [comment]
hey no worries, I don't take this as a complaint 🙂 I'm actually curious as to what's wrong

you can clone the branch I created either with git or with direct download : https://github.com/msarilar/EDEngineer/archive/task/no-toast-code.zip

in the unzipped archive, you'll see a solution file EDEngineer.sln which you'll need to open in Visual Studio. you'll be able to debug (F5) once the solution is loaded, but you might encounter compilation errors (make sure you're using VS2017)

**Comment by JimLindsey** [comment]
I have been out of town and not had the chance to look at this until today. Not certain if it is update x.28 of EDEngineer or completely uninstalling then installing .Net framework 4.7.1,, but whichever it was.  EDEngineering is no longer crashing when adding Experimentals to the shopping list.
