### ISSUE TITLE
Engeneering trade panel questions

### ISSUE THREAD

**Issue by mendocinotim** [msarilar/EDEngineer#430]
I am not understanding the trade panels (if that's the right name for these?), and what the numbers they provide all mean.
In the following screenshot..

![engeneering trade panels](https://user-images.githubusercontent.com/1205038/42179356-795e7e22-7de8-11e8-9c89-d69bd641c494.jpeg)

1)
The top part, where it says: "9 EXQUISITE TRADE CRYSTALS"..
What is the number "9" representing? Do I read this to mean:
"To obtain 9 of these" - or does it mean something else?

2)
In the lower part: I think (where it says "54 CORE DYNAMIC COMPOSITES") it's saying that if I have 54 of them, then I can trade those for the 9 EXQUISITE FOCUS CRYSTALS - is that how I should read it? Or does it mean something else.

3)
I understand that it's telling me that I have 24 (so far).
But what is the percent (in parens) referring to?
"( 225% )" of what?

I have read all the tool tips - although they do not remain very long, which is not convenient, as I need to actually grok their meanings - my comprehension is slow while the tool tips are too fast for me. LOL; although they do not explain the answers to the questions I just posted here (as far as I can tell).

If you can help me understand these a little better, I would be most appreciative.

Again - thanks (in advance) for the help; and for this really cool tool.

**Comment by msarilar** [comment]
I agree it can be a bit confusing and there's no manual for this, but I tried to put condensed information without cluttering the UI too much.

Basically you need 9 Exquisite Crystals to complete all the blueprints in your shopping list. You might need 10 and already have 1 for instance.

Now the app computes what material trades can be interesting to acquire the crystals and list them by how much you'd need. Here you need 54 core composites to trade, and you have 24 of them (not enough, otherwise it would be written 100% or less). The suggestions below are worse but still possible.

This specific material trade suggestion is not particularly interesting as you actually don't have all required materials to fully acquire the exquisite crystals you need and that's why the suggestion appears in orange. Blue suggestions indicate that you can fully obtain what you need by trading, like the one below for the 1 shield soak analysis that you need.

**Comment by mendocinotim** [comment]
Okay, so I'm understanding 1 & 2 (from my original question). The percent one still needs further explaining however - if you would be willing to give it a try(?), I would overflowing with (still more) appreciation for your efforts. LOL

**Comment by msarilar** [comment]
Don't worry about it, I'm aware the UI can be confusing :)

The percentage indicates how big of an impact it would be on your cargo to trade: 54 is 225% of 24 (`24 * 2.25 = 54`)

a more reasonable example would be like if you needed 12 of them and had 24 in your cargo, then it would show 50% instead (i.e. you would have to trade half of all your core composites to get all of the crystals you need)

**Comment by mendocinotim** [comment]
Got it.
It is confusing though.
Perhaps showing it as a ratio would make a little more sense.
For example using your example: where you have 24 on hand and had to give up half of them to acquire something, then you would be sacrificing at a ration of 2:1 (i.e., -2:1) = the minus shows it would be a sacrifice (for the greater good).

But, on the other hand ...
Maybe the percentage idea (or the ratio I was thinking might be better) are both bad ideas.

I think if you were to add the words "**would help**" at the end of the opening phrase, 
as in..
"54 CORE DYNAMIC COMPOSITES **would help**..
YOU HAVE 24".

That would have made sense to me.
I think that would be a better way to convey the important idea here.

Give that some consideration, as a possible alternative..

**Comment by mendocinotim** [comment]
In fact.. adding the words "to trade", after the second part of the phrase would make it completely understandable; as in.. 
"54 CORE DYNAMIC COMPOSITES **would help**..
YOU HAVE 24 **to trade**".

**Comment by mendocinotim** [comment]
Well anyway.. Thanks for getting back to me. Now I know how to use it.
Keep up the good work.
Yours,
 - Timothy
