### ISSUE TITLE
Correct Path for Journal, but wrong date shown

### ISSUE THREAD

**Issue by DrewBornt** [msarilar/EDEngineer#525]
<img width="621" alt="ED Path with Journal" src="https://user-images.githubusercontent.com/24900839/75629614-151c5380-5ba9-11ea-854e-6ef3a5690eb8.png">
<img width="1048" alt="edengineer showing wrong date" src="https://user-images.githubusercontent.com/24900839/75629616-1a799e00-5ba9-11ea-8a03-ddbd87c5d59c.png">

In the above images, the program shows the wrong date/time but is pointing to the correct path for my elite dangerous journal. EDEngineer is version 1.1.4.9

Would deleting everything in that save folder and reloading the game and edengineer potentially fix this?

**Comment by msarilar** [comment]
it could be an access right issue, e.g. Windows blocking EDEngineer from reading the file

running the app as admin might give you some results.

otherwise, try changing the folder to a different location then back to where it's supposed to be (you can change the folder location by clicking on the path in your screenshot of the app)
