### ISSUE TITLE
EDEngineer can't find my logs and the ingredients list isn't populated

### ISSUE THREAD

**Issue by Urthor** [msarilar/EDEngineer#58]
First of all amazing app btw.  When it gets running it looks like it'll be amazing. 

I've run into an issue running this however, my installation's paths are irregular, my bindings files are located in C:\Users\User\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings for example, and EDE isn't managing to track down the correct log file it needs.

When I launch the program ingame it displays me at zero materials and commodities for all the options, nothing.  Obviously if it says I have zero sulphur and can't craft lvl 1 mods when I'm at 900 plus materials something isn't exactly right.   Assume from your Github notes this is irregular and it's supposed to pick up some approximation of what my materials are if it has found the log.

Which leads to the final question, what's the exact name/contents/location of the log file that's needed to run EDE?  If I know the name I can track it down by the contents/filetype wherever it has gone.

**Comment by msarilar** [comment]
The app tries to go to `C:\Users\%USERNAME%\Saved Games\Frontier Developments\Elite Dangerous` directory. If it doesn't exists, or if it contains no log file, it will warn you. If your logs are located somewhere else, you'll have to find the directory yourself unfortunately.

The directory should contain plenty of files with names like `Journal.161030193855.01.log`. 

Beware to not use the netlog directory, it won't work either. You're looking for the Commander's Log directory !

Good luck

**Comment by bubbavox** [comment]
I got this error, and had to manually specify my directory. and I suspect it is because I had moved many of my "special" directories from `C:\Users\%USERNAME%\` to a different drive (`Desktop, Downloads, Saved Games,` etc).  Windows registers the relocation of these special folders, and most apps redirect to it, including ED -- maybe there's a way to refer to that path, e.g. '%USERPROFILE%' ?

**Comment by bubbavox** [comment]
I got this error -- I suspect because I moved `Saved Games` and other special `%USERPROFILE%` directories.  Then I _think_ it ignored my specification of the correct folder during installation -- unless the error was mine -- but in any case I was able to change the folder after install, by clicking on the dark cyan text in bottom right of app window.  Things seem to be working so far.

Maybe EDEngineer could be coded to look in `%USERPROFILE%\Saved Games\Frontier Developments\Elite Dangerous` ?

**Comment by Youda008** [comment]
If you can figure out a way to call the C Win32 API from C#, then you can automate searching for the log directory by finding `Saved Games` this way https://stackoverflow.com/questions/54499256/how-to-find-the-saved-games-folder-programmatically-in-c-c and just appending `\Frontier Developments\Elite Dangerous`.
