### ISSUE TITLE
How is 

### ISSUE THREAD

**Issue by rosscarlson** [msarilar/EDEngineer#620]
Seems 2 Odyssey engineers are missing from the "Unlock" section

Hero Ferrari
-

**Comment by jpacelli62** [comment]
Jude Navarro, Domino Green, Hero Ferrari are not in the "Unlock" section because they don't need any item/data to be discoreved/unlocked.
See :
https://elite-dangerous.fandom.com/wiki/Hero_Ferrari
https://elite-dangerous.fandom.com/wiki/Domino_Green
https://elite-dangerous.fandom.com/wiki/Jude_Navarro
However they appear in the unlocking conditions of other engineers. 
Eg to unlock Wellington Beck:
Provide 15 units of Settlement Defence Plans to Hero Ferrari to learn about Wellington Beck.
Sell 25 total units of Classic Entertainment, Multimedia Entertainment, and/or Cat Media to Bartenders.
You see Bartender an Hero Ferrari under the Wellington Beck row
